config/routes.rb
Rails.application.routes.draw do
  ############ User Route ###############################
  get 'signup', to: 'users#new', as: 'signup'
  get 'login' => 'users#login', as: "login"
  post 'login' => 'users#handle_login'
  delete 'logout' => 'users#logout', as: "logout"
  post '/users', to: 'users#create'
  get '/users/:id', to: 'users#show', as: 'user'
  get '/users/:id/edit', to: 'users#edit', as: 'edit_user'
  patch '/users/:id', to: 'users#update'
############## Quesiton Route ###########################
  get "/questions", to: "questions#index", as: 'questions'
  get "/users/:user_id/questions/new", to: 'questions#new', as: "new_question"
  post "questions", to: 'questions#create'
  get "/users/:user_id/questions/:id", to: "questions#show", as: 'question'
  get "/questions/:id/edit", to: 'questions#edit', as: "edit_question"
  patch "/users/:user_id/questions/:id", to: "questions#update"
  delete "/users/:user_id/questions/:id", to: 'questions#destroy', as: "delete_question"
#################### ugly nested route #########################
  root 'users#home'
#################### Answer Route #############################
  get "questions/:id/answers/new", to: "answers#new", as: "new_answer"
  post 'answers', to: "answers#create"
  get 'answers/:id', to: "answers#show", as: "answer"
  get 'answers/:id/edit', to: "answers#edit", as: "edit_answer"
  patch 'answers/:id', to: "answers#update"
  delete 'answers/:id', to: "answers#destroy", as: "delete_answer"
#################### Answer Route #############################
  get "categories", to: "categories#index", as: "categories"
  get "categories/:id", to: "categories#show", as: "category"
  patch "categories/:id", to: "categories#update"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user, optional: true
  has_many :answers, dependent: :destroy
  
  has_many :ques_lans, dependent: :destroy
  has_many :categories, through: :ques_lans
  
  accepts_nested_attributes_for :categories
  validates :title, :content, presence: true


  def category_name
     a = self.categories.pluck(:name)
  end
  
  def categories_attributes=(category_attributes)
    category_attributes.values.each do |category_attribute|
      category_attribute[:name] = category_attribute[:name].titleize
      category = Category.find_or_create_by(category_attribute)
      self.categories << category
    end
  end


end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
    before_action :get_question, only: [:show, :edit, :update, :destroy]

    def index
        @questions = Question.all
    end

    def new
        # byebug
        @question = @current_user.questions.build
    end

    def create
        # byebug
        @question = @current_user.questions.create(question_param)
        if @question.id.nil?
            flash[:error] = @question.errors.full_messages
            redirect_to new_question_path(@current_user)
        else
            redirect_to user_path(@current_user)
        end
    end

    def update
        if @question.update(question_param)
        redirect_to user_path(@current_user)
        else
            flash[:error] = "invalid input"
            redirect_to edit_question_path(@question)
        end
    end

    def destroy
        @question.destroy
        redirect_to user_path(@current_user)
    end


    private

    def get_question
        @question = Question.find_by_id(params[:id])
    end
    def question_param
        params.require(:question).permit(:user_id,:title,:content,category_ids:[] )#categories_attributes: [:name]
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/edit.erb
<%=render "users/nav"%>
<div class="row" id="question_form">
  <div class="col-md-4 col-md-offset-4">
  <%# <div class="col-md-4 col-md-offset-4"> %>
  <%= bootstrap_form_for(@question) do |f| %>
      <h1 class= "welcome">Post a question</h1>
      <%= render "users/error"%>
      <%=f.text_field :title, placeholder: "Title", class: "form-control input-lg"%>
      <%= f.collection_check_boxes :category_ids, Category.all, :id, :name, wrapper: {class: "cp-container-class"}%>
      <%=f.text_area :content, rows: 7, placeholder: "Start here...",class:"form-control input-lg"%>
      <%=f.submit "save", class: "btn-block btn-primary btn-lg"%>
    <%end%>
  </div>
</div>
</div>

app/views/questions/index.erb
<%= render "users/nav"%>

<div class="row">
  <div class="col-md-6 col-md-offset-3 question_index">
      <% @questions.each do |question| %>
      <%# <div class="col-md-6"> %>
      <div class= "card">
          <div class="card-body">
            <h5><%=link_to question.title, question_path(@current_user, question),class:"card-title question_index"%></h5>
            <h5 class="question_show_answer"><%=pluralize(question.answers.count,"answer")%></h5>
            <% question.categories.uniq.each do |category|%>
            <span><%=link_to category.name, category_path(category)%></span>
          <%end%>
          <h6 class="question_show_username">by - <%=question.user.full_name%></h6>
            <p class="question_index_btn"><%=link_to "more info", question_path(@current_user, question), class:"btn btn-primary"%></p>
          </div>
      </div>
  <%# </div> %>
  <%end%>
</div>

app/views/questions/new.erb
<%=render "users/nav"%>
<div class="row" id="question_form">
  <div class="col-md-4 col-md-offset-4">
  <%# <div class="col-md-4 col-md-offset-4"> %>
  <%= bootstrap_form_for(@question) do |f| %>
      <h1 class= "welcome">Post a question</h1>
      <%= render "users/error"%>
      <%=f.text_field :title, placeholder: "Title", class: "form-control input-lg"%>
      <%= f.collection_check_boxes :categories, Category.all, :id, :name%>
      <%=f.text_area :content, rows: 7, placeholder: "Start here...",class:"form-control input-lg"%>
      <%=f.submit "Post", class: "btn-block btn-primary btn-lg"%>
    <%end%>
  </div>
</div>
</div>

app/views/questions/show.erb
<%=render "users/nav"%>

<div class="row">
    <div class="col-md-8 col-md-offset-2 question_show">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title"><strong><%= @question.title%></strong></h5>
                <%=link_to "Answer", new_answer_path, class:"btn btn-primary question_show_btn"%>
                <hr>
                <div class="question-show-answer-section">Author:
                <div><%= @question.content%></div>
                </div>
                <hr/>
                 
                <div class="row">
                <div class="col-md-10 col-md-offset-1">
                 <% @question.answers.each do |answer|%>
                <div class="question-show-answer-section"><%= answer.user.full_name%> answered:<br/>
                    <div class= "quesiton-show-answer-content"><%= answer.content%><br/>
                            <%if answer.user == @current_user %>
                                <%=link_to "edit", edit_answer_path(answer), class: "question_link_show_edit_and_delete"%> | 
                                <%=link_to "delete", delete_answer_path(answer), :method => :delete , class: "question_link_show_edit_and_delete"%>
                            <%end%>
                        </div>
                    <hr/>
                </div>
                <%end%>
                </div>
                </div>
        </div>
    </div>
</div>