config/routes.rb
Rails.application.routes.draw do
  ############ User Route ###############################
  get 'signup', to: 'users#new', as: 'signup'
  get 'login' => 'users#login', as: "login"
  post 'login' => 'users#handle_login'
  delete 'logout' => 'users#logout', as: "logout"
  post '/users', to: 'users#create'
  get '/users/:id', to: 'users#show', as: 'user'
  get '/users/:id/edit', to: 'users#edit', as: 'edit_user'
  patch '/users/:id', to: 'users#update'
############## Quesiton Route ###########################
  get "/questions", to: "questions#index", as: 'questions'
  get "/users/:user_id/questions/new", to: 'questions#new', as: "new_question"
  post "questions", to: 'questions#create'
  get "/users/:user_id/questions/:id", to: "questions#show", as: 'question'
  get "/questions/:id/edit", to: 'questions#edit', as: "edit_question"
  patch "/users/:user_id/questions/:id", to: "questions#update"
  delete "/users/:user_id/questions/:id", to: 'questions#destroy', as: "delete_question"
#################### ugly nested route #########################
  root 'users#home'
#################### Answer Route #############################
  get "questions/:id/answers/new", to: "answers#new", as: "new_answer"
  post 'answers', to: "answers#create"
  get 'answers/:id', to: "answers#show", as: "answer"
  get 'answers/:id/edit', to: "answers#edit", as: "edit_answer"
  patch 'answers/:id', to: "answers#update"
  delete 'answers/:id', to: "answers#destroy", as: "delete_answer"
#################### Answer Route #############################
  get "categories", to: "categories#index", as: "categories"
  get "categories/:id", to: "categories#show", as: "category"
  patch "categories/:id", to: "categories#update"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    has_one_attached :avatar
    has_many :questions, -> {order ("title ASC")}, dependent: :destroy
    accepts_nested_attributes_for :questions, allow_destroy: true
    has_many :answers
    accepts_nested_attributes_for :answers, allow_destroy: true
    
################################ Validation ###########################################
    before_save {self.email = email.downcase } #or { email.downcase!}
    
    validates :first_name, :last_name, presence: true, length: { maximum: 50 }
   
    validates :email, presence: true,
                    length: { maximum: 50 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i},
                    uniqueness: { case_sensitive: false }
    has_secure_password
    
    validates :password, length: { minimum: 6 }, allow_blank:true;

###########################################################################################
    def full_name
        "#{self.first_name} #{self.last_name}"
    end

    def question_arr
        arr = []
        self.answers.each do |answer|
            arr << answer.question
        end
        arr.uniq
    end




    # <% @user.question_arr.each do |question|%>
    #     <li>
    #         <%=link_to question.title, question_path(@current_user, @user.question_arr.find(title: "question"))%>
    #     </li>
    # <%end%>

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :get_user, only: [:show, :edit, :update, :destroy]
    skip_before_action :auhorized_to_see_page, only: [:handle_login,:new,:create,:login, :home]

    def handle_login
        # byebug
        #use find_by instead of find because find raise exception error when user is nil, find_by will just return nil
        user = User.find_by(email: params[:session][:email].downcase)
        # if the email is in the db, verify the password
        if user && user.authenticate(params[:session][:password])
          log_in user
          redirect_to user_path(user)
        else
          # byebug
          flash[:danger] = "Invalid email/password"
          redirect_to login_path
        end
    end

      def logout
        session.delete(:user_id)
        @current_user = nil
        redirect_to "/"
    end

    def new
        @user = User.new
    end

    def create
        @user = User.create(user_param)
        @user.avatar.attach(params[:avatar])
        if @user.valid?
            log_in @user
            redirect_to user_path(@user)
        else
            # byebug
            flash[:errors] = @user.errors.full_messages
            redirect_to signup_path
        end
    end

    def show
        @user = @current_user
        @questions = @user.questions
        @answers = @user.answers
    end

    def edit
        @user = @current_user
    end

    def update
        # byebug
        if User.find_by(email: params[:user][:email]) == @user || User.find_by(email: params[:user][:email]).nil?
            @user.update(user_param)
            redirect_to user_path(@user)
        else
            flash[:errors] = "Email is taken"
            redirect_to edit_user_path
        end
    end


    private
    def get_user
        @user = User.find(params[:id])
    end

    def user_param
        params.require(:user).permit(:first_name,
            :last_name,
            :password,
            :email,
            :avatar,
            question_ids:[],
            questions_attributes: [:title, :content])
    end
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_for(user)
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
        image_tag(gravatar_url, alt: user.full_name)
    end
end

app/views/users/_error.erb
<div>
      <%if flash %>
        <% flash.each do |message_type, message| %>
            <div class="alert alert-danger"">
            <%if message.class == Array%>
                You have <%= pluralize(message.count, "error")%>.
                <ul>
                <% message.each do |msg|%>
                    <li><%=msg%></li>
                <%end%>
                </ul>
                <ul>
                    <%else%>
                    <li><%= message %></li>
                    <%end%>
                </ul>
            </div>
        <%end%>
      <%end%>
</div>

app/views/users/_home.erb
 <div class="navbar navbar-fixed-top navbar-custom" role="navigation">
	<div class="container-fluid">
		<div class="collapse navbar-collapse">
			<ul class="nav navbar-nav">
				<li><a href="#"><span class="glyphicon glyphicon-home"></span> Home</a></li>
				<li><a href="#shop"><span class="glyphicon glyphicon-globe"></span> About</a></li>
				<li><a href="#support"><span class="glyphicon glyphicon-phone-alt"></span> Support</a></li>
			</ul>
            <ul class="nav navbar-nav navbar-right">
            <!--################### use .html_safe inside of link_to for the glyphicon ################ -->
                <li><%=link_to '<i class="glyphicon glyphicon-user"></i> Sign up'.html_safe, new_user_path%></li>
                <li><%=link_to '<i class="glyphicon glyphicon-log-in"></i> Log in'.html_safe, login_path%></li>
            </ul>
		</div>
    </div>
</div>

<!--
 <li><%=link_to login_path%><i class="glyphicon glyphicon-user"></i></li>


 <li class="glyphicon glyphicon-user"><span ></span></li>
<%=link_to "Signup", new_user_path%>
-->

app/views/users/_nav.erb
 <div class="navbar navbar-fixed-top navbar-custom" role="navigation">
	<div class="container-fluid">
		    <ul class="nav navbar-nav active">
            <!--################### use .html_safe inside of link_to for the glyphicon ################ -->
          <li><%=link_to '<i class = "glyphicon glyphicon-home" style="font-size:18px"></i> Home'.html_safe, user_path(@current_user)%></li>
          <li><%=link_to '<i class="glyphicon glyphicon-th-list" style="font-size:18px"></i> Browse Questions'.html_safe, { :controller=> 'questions', :action => 'index' }%></li>
          <li><%=link_to '<i class="glyphicon glyphicon-book" style="font-size:18px"></i> Categories'.html_safe, { :controller=> 'categories', :action => 'index' }%></li>
          <li><%=link_to '<i class="glyphicon glyphicon-education" style="font-size:18px"></i> Post a Question'.html_safe, new_question_path(@current_user)%></li>
          </ul>
            <ul class="nav navbar-nav navbar-right active">
            <li><%=link_to '<i class="glyphicon glyphicon-user" style="font-size:18px"></i> Profile'.html_safe, edit_user_path(@current_user)%></li>
            <li><%=link_to '<i class="glyphicon glyphicon-log-out" style="font-size:18px"></i> Log out'.html_safe, logout_path, method: :delete%></li>
            </ul>
    </div>
</div>

<!--reserved-->


<!--reserved-->

app/views/users/edit.erb
<% if logged_in? %>
<div> <%= render "users/nav"%> </div>
<%end%>
<div class="row" id="form">
  <div class="edit col-md-4 col-md-offset-4">
    <%= form_for @user do |f|%>
      <h1 class= "welcome">Update profile</h1>
      <br>
      <%= render "users/error"%>
      <div class="row">
      <div class="input-group ">
        <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
        <span><%=f.text_field :first_name, placeholder: "First Name", class: "form-control input-lg"%></span>
      </div>
      <div class="input-group">
        <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
        <span><%=f.text_field :last_name, placeholder: "Last Name", class: "form-control input-lg"%></span>
      </div>
      <div class="input-group">
        <span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>
        <%=f.email_field :email, placeholder: "Enter email", class: "form-control input-lg"%>
      </div>
      <div class="input-group">
        <span class="input-group-addon"><i class="glyphicon glyphicon-lock "></i></span>
        <%=f.password_field :password, placeholder: "Password",class:"form-control input-lg"%>
      </div>
      <br>
      <%=f.submit "save", class: "btn-block btn-primary btn-lg"%>
    <%end%>
  </div>
</div>

app/views/users/home.html.erb
<button class="split centered">
<h1>Codera</h1>
<p class="home_subtitle">“First, solve the problem. Then, write the code.” – John Johnson</p>
<div class="homepage_1 btn btn-primary"><%=link_to "login", login_path%></div>
<div class="or">OR</div>
<div class="homepage_2 btn btn-primary"><%=link_to "signup", signup_path%></div>

app/views/users/login.html.erb
<!-- ############################## login form ##################################### -->
<div class="row" id="form">
  <div class="col-md-4 col-md-offset-4">
    <%= form_for(:session, url: login_path) do |f|%>
      <h1 class= "welcome">Welcome to Codera</h1>
      <br>
      <%= render "users/error"%>
      <div class="input-group">
        <span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>
        <%=f.email_field :email, placeholder: "Enter email", class: "form-control input-lg"%>
      </div>
      <div class="input-group">
        <span class="input-group-addon"><i class="glyphicon glyphicon-lock "></i></span>
        <%=f.password_field :password, placeholder: "Password",class:"form-control input-lg"%>
      </div>
      <br>
      <%=f.submit "Log in", class: "btn-block btn-primary btn-lg"%>
      <h6 class="signup_link">Not a member? <%=link_to "Sign up now!", signup_path%></h6>
    <%end%>
  </div>
</div>
  <!-- ############################## login form ##################################### -->

app/views/users/new.erb
        <!-- ############################## signup form ##################################### -->
<div class="row" id="form">
  <div class="col-md-4 col-md-offset-4">
    <%= form_for @user do |f|%>
      <h1 class= "welcome">Welcome to Codera</h1>
      <br>
      <%= render "users/error"%>
      <div class="input-group col">
        <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
        <%=f.text_field :first_name, placeholder: "First Name", class: "form-control input-lg"%>
      </div>
      <div class="input-group col">
        <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
        <%=f.text_field :last_name, placeholder: "Last Name", class: "form-control input-lg"%>
      </div>
      <div class="input-group">
        <span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>
        <%=f.email_field :email, placeholder: "Enter email", class: "form-control input-lg"%>
      </div>
      <div class="input-group">
        <span class="input-group-addon"><i class="glyphicon glyphicon-lock "></i></span>
        <%=f.password_field :password, placeholder: "Password",class:"form-control input-lg"%>
      </div>
      <br/>
      <%=f.submit "Sign up", class: "btn-block btn-primary btn-lg"%>
      <h6 class="signup_link">Already a member? <%=link_to "log in", login_path%></h6>
    <%end%>
  </div>
</div>
        <!-- ############################## signup form ##################################### -->

app/views/users/show.erb
<% if logged_in? %>
<div> <%= render "users/nav"%> </div>
<%end%>

<div class="row user_home_page">
  <div class="user_home_section_1">
   <div class="user_full_name_show"><%= gravatar_for @user %>Hi:<%=@user.first_name%></div>
  </div>
</div>

<hr/>

<div class="row user_home_page">
  <div class="col-md-8 col-md-offset-2 user_home_section_2">
 <div class="user-home-page-font"> Posted Questions </div><hr/>
            <% @questions.each_with_index do |question,index| %>
            <div class="user_home_page-question-font"><%=index+1%>.
            <%=link_to question.title, question_path(@current_user,question), class: "user_home_page-question-font"%>
            <div>
            <%=pluralize(question.answers.count,"answer")%>
            <%=link_to "edit", edit_question_path(question) %>
            <%=link_to "delete", delete_question_path(@current_user,question), :method => :delete %>
            </div>
            </div><hr/>
            <%end%>
  </div>
</div>

<div class="row user_home_page">
  <div class="col-md-8 col-md-offset-2 user_home_section_3">
 <div class="user-home-page-font"> Answered Questions</div><hr/>
        <%@user.question_arr.each_with_index do |question,index|%>
        <span class= "user_home_page-question-font"><%=index+1%>. </span>
        <%=link_to question.title, question_path(@current_user,question), class: "user_home_page-question-font"%>
        <div class="user_home_page-question-font"><%=pluralize(question.answers.count,"answer")%></div>
        <hr/>
        <%end%>
  </div>
</div>